import { type CartLineItem, type CartState } from '../types';

export type CartAction =
  | { type: 'cart/hydrated'; payload: { items: CartLineItem[] } }
  | { type: 'cart/itemAdded'; payload: { item: Omit<CartLineItem, 'lineId'>; lineId: string } }
  | { type: 'cart/itemRemoved'; payload: { lineId: string } }
  | { type: 'cart/cleared' };

export const INITIAL_CART_STATE: CartState = { items: [] };

/**
 * Pure reducer for the shopping cart.
 *
 * Each add operation produces a new line (no merging by variant, no
 * quantity field) — this matches the brief's "remove individual
 * products" requirement and keeps the model trivial.
 *
 * The `lineId` is generated by the caller rather than here, so the
 * reducer stays deterministic and easy to unit-test.
 */
export function cartReducer(state: CartState, action: CartAction): CartState {
  switch (action.type) {
    case 'cart/hydrated':
      return { items: action.payload.items };

    case 'cart/itemAdded': {
      const { item, lineId } = action.payload;
      return { items: [...state.items, { ...item, lineId }] };
    }

    case 'cart/itemRemoved':
      return {
        items: state.items.filter((line) => line.lineId !== action.payload.lineId),
      };

    case 'cart/cleared':
      return INITIAL_CART_STATE;

    default: {
      const _exhaustive: never = action;
      return _exhaustive;
    }
  }
}

export function selectTotalPrice(state: CartState): number {
  return state.items.reduce((sum, line) => sum + line.storage.price, 0);
}

export function selectTotalCount(state: CartState): number {
  return state.items.length;
}
